document.write('<!-- 用来产生编辑状态的ActiveX控件的JS脚本-->   ');
document.write('<!-- 因为微软的ActiveX新机制，需要一个外部引入的js-->   ');
document.write('<object id="TANGER_OCX" classid="clsid:A39F1330-3322-4a1d-9BF0-0BA2BB90E970"    ');
/*使用绝对路径就可以，使用相对路径就不行，还没有搞定*/
//document.write('codebase="http://www.ntko.com/admin/ocv14_test.nsf/vwOCX/OfficeControl.cab/$FILE/OfficeControl.cab#version=5,0,1,6" width="100%" height="100%">   ');
document.write('codebase="http://localhost:8080/bo/officecontrol/OfficeControl.cab#version=5,0,1,6" width="100%" height="'+($(window).height()-33)+'px">   ');
document.write('<param name="BorderStyle" value="1">   ');
document.write('<param name="BorderColor" value="14402205">   ');
document.write('<param name="TitlebarColor" value="15658734">   ');
document.write('<param name="TitlebarTextColor" value="0">   ');
document.write('<param name="Caption" value="NTKO OFFICE文档控件V5.0 http://www.ntko.com">   ');
document.write('<param name="IsShowToolMenu" value="-1">   ');
document.write('<param name="IsUseUTF8URL" value="-1">   ');
document.write('<param name="MaxUploadSize" value="10000000">   ');
document.write('<param name="CustomMenuCaption" value="我的菜单">   ');
document.write('<param name="MenubarColor" value="14402205">   ');
document.write('<PARAM NAME="MenuButtonColor" VALUE="16180947">   ');
document.write('<param name="MenuBarStyle" value="3">   ');
document.write('<param name="MenuButtonStyle" value="7">   ');
document.write('<SPAN STYLE="color:red">不能装载文档控件。请在检查浏览器的选项中检查浏览器的安全设置。</SPAN>   ');
document.write('</object>   ');
